### ISSUE TITLE
Update to 230 from russel5?

### ISSUE THREAD

**Issue by Flamefire** [cryptomilk/android_kernel_sony_msm8998#99]
It seems there is a 230 kernel version for msm8998: https://github.com/russel5/aex_kernel_sony_msm8998

Not sure how the 2 repos differ but could they maybe be merged to not spend time twice? Or at least cherry-pick the updates from there to here?

**Comment by cryptomilk** [comment]
@derfelot didn't have time to update it yet.

**Comment by derfelot** [comment]
I'll get to this either tonight or tomorrow night, including the caf updates. they implemented a bunch of fixes for clang compilation, so i would like to revert our current fixes to stay as clean as possible with la.um.8..4

**Comment by vincentvidal** [comment]
@derfelot @cryptomilk There is apparently the same memory leak problem for camera with that kernel. I don't know if you saw (https://github.com/cryptomilk/android_vendor_sony_lilac/pull/15), embedding a few blobs from taimen solves the problem...

**Comment by derfelot** [comment]
yes we saw that, but we are hoping that we are close to a fix. we definitely prefer to fix it in the source, rather than kanging blobs from a different device. but thanks for the heads-up ;)

**Comment by vincentvidal** [comment]
OK great! This would be much better of course, I hope you'll succeed... Thanks for your efforts :-)

**Comment by cryptomilk** [comment]
`hardware/qcom-caf/msm8998/display/gralloc/gr_priv_handle.h +95`

Add an `int dummy` and the memory issue is fixed but all pictures will be green :-)

**Comment by vincentvidal** [comment]
I saw that elsewhere yes. Actually I prefer kanged blobs than green pictures ;-)

**Comment by cryptomilk** [comment]
It means we are near but haven't fixed it yet.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> but we are hoping that we are close to a fix

@derfelot I've never imagined this leak could be so hard. Really appreciate you guys 👍

**Comment by derfelot** [comment]
Fixed with https://github.com/cryptomilk/android_kernel_sony_msm8998/pull/100

**Comment by derfelot** [comment]
> `hardware/qcom-caf/msm8998/display/gralloc/gr_priv_handle.h +95`
> 
> Add an `int dummy` and the memory issue is fixed but all pictures will be green :-)

I now managed to fix the leak and only get green pictures in low light conditions. The plot thickens...

**Comment by derfelot** [comment]
I figured out that the leak issue is caused by a CAF commit that messes about with the internal structure of the private_handle_t. Reverting that one will fix the leak, but the green image issue persists. More specifically, i found out that at ISO 50 all pictures are fine, at 100 and 200 there are some artefacts and starting with 200 all pictures have a green tint.

I have spent pretty much all my "android time" of the last month (or more) trying to fix this and I am getting tired of it :) I have now tried kanging the blobs from taimen as suggested and everything seems to work indeed (including Wifi display).

So even though I am very much against kanging blobs from other devices unless absolutely needed (e.g. the display SDM blobs to get LiveDisplay working on Android 10 CAF display tag - there is no way around this) I now would like to go ahead and do it for now so I can focus on other remaining issues. There probably is a way to fix the green picture issue in the source but I am out of ideas.

**Comment by hakkikaancaliskan** [comment]
> I figured out that the leak issue is caused by a CAF commit that messes about with the internal structure of the private_handle_t. Reverting that one will fix the leak, but the green image issue persists. More specifically, i found out that at ISO 50 all pictures are fine, at 100 and 200 there are some artefacts and starting with 200 all pictures have a green tint.
> 
> I have spent pretty much all my "android time" of the last month (or more) trying to fix this and I am getting tired of it :) I have now tried kanging the blobs from taimen as suggested and everything seems to work indeed (including Wifi display).
> 
> So even though I am very much against kanging blobs from other devices unless absolutely needed (e.g. the display SDM blobs to get LiveDisplay working on Android 10 CAF display tag - there is no way around this) I now would like to go ahead and do it for now so I can focus on other remaining issues. There probably is a way to fix the green picture issue in the source but I am out of ideas.

I agree with you, that's better for now. Thanks for everything dev.
I just want to ask you a question. Are you going to release a new build? If yes, in bliss rom GPS fixed, are you going to include that fix in los?
Also is there a plan in the future for official los support?

Again, thanks for keeping poplar alive ☺️

**Comment by Flamefire** [comment]
> I figured out that the leak issue is caused by a CAF commit that messes about with the internal structure of the private_handle_t. Reverting that one will fix the leak, but the green image issue persists. More specifically, i found out that at ISO 50 all pictures are fine, at 100 and 200 there are some artefacts and starting with 200 all pictures have a green tint.

Thanks a lot for your work. Would it be possible for you to open an issue where you briefly explain the problem and what you found and tried already? E.g linking to the mentioned CAF commit. Even though you didn't fix the problem it would be great if the work you did wasn't lost and someone can pick up where you left later without doing the same again you already did

**Comment by derfelot** [comment]
i would have put all the details into the commit message of kanging the blobs, but @cryptomilk and I are still talking about the issue.

**Comment by derfelot** [comment]
> I just want to ask you a question. Do you have a plan to release a new build? If yes, in bliss rom GPS fixed, are you going to include that fix in los?

Yes I p;lan on making builds again. As for the GPS issue (which I don't have myself, GPS is working fine here) I would have to see what they have done to fix it.

> Also is there a plan in the future for official los support?

I would like to, but we need to sort out the remaining issues first.

**Comment by shank03** [comment]
> I would have to see what they have done to fix it.

@MFShujath do you mind sharing the fix ?

**Comment by MFShujath** [comment]
> > I just want to ask you a question. Do you have a plan to release a new build? If yes, in bliss rom GPS fixed, are you going to include that fix in los?
> 
> Yes I p;lan on making builds again. As for the GPS issue (which I don't have myself, GPS is working fine here) I would have to see what they have done to fix it.
> 
> > Also is there a plan in the future for official los support?
> 
> I would like to, but we need to sort out the remaining issues first.

Hey @derfelot 

I used gps blobs pulled from stock by @linckandrea 

https://github.com/linckandrea/android_vendor_sony_poplar

This fixed the GPS issue.
I

**Comment by derfelot** [comment]
Strange, we pull all the GPS blobs from stock as well, so I don't see the difference.

**Comment by MFShujath** [comment]
> Strange, we pull all the GPS blobs from stock as well, so I don't see the difference.

other changes that may be related are  
Disabling Treble and removing current Boardvndk

https://github.com/Yoshino-StockDevelopment/android_device_sony_poplar/commit/b0881b713db2a5e22e5e822eaa7a60b759130b51

**Comment by derfelot** [comment]
> > Strange, we pull all the GPS blobs from stock as well, so I don't see the difference.
> 
> other changes that may be related are
> Disabling Treble and removing current Boardvndk
> 
> [Yoshino-StockDevelopment/android_device_sony_poplar@b0881b7](https://github.com/Yoshino-StockDevelopment/android_device_sony_poplar/commit/b0881b713db2a5e22e5e822eaa7a60b759130b51)

that only applies to maple since it lacks a vendor partition and hence is not treble compliant - it was released half a year too early for that.

But I'll have a look at gps

**Comment by derfelot** [comment]
looks like i finally managed to fix both the leak and green picture at low iso issue in source. will try to push a fix tomorrow

**Comment by shank03** [comment]
@MFShujath do you think that the vendor.xml might have something to do with GPS fix ?

**Comment by MFShujath** [comment]
> @MFShujath do you think that the vendor.xml might have something to do with GPS fix ?
> 
> Or something you might have done in overlay ?

I dont think so, I use the same manifest,xml and overlays for maple and poplar.
for maple gps is still not working, I will pull blobs from stock and try again to see how it goes on maple.

**Comment by derfelot** [comment]
Here's a diff you can apply to `hardware/qcom-caf/msm8998/display` to fix the camera issues:

https://pastebin.com/2EiGqsRv

You also need to set `TARGET_USES_SONY_STOCK_CAMERA := true` in the BoardConfigPlatform.mk in yoshino

Please let me know how it goes. I uploaded a change for this to LOS gerrit, but it's private till we have thoroughly tested it.

**Comment by idyllic-blue** [comment]
> Here's a diff you can apply to `hardware/qcom-caf/msm8998/display` to fix the camera issues:
> 
> https://pastebin.com/2EiGqsRv
> 
> You also need to set `TARGET_USES_SONY_STOCK_CAMERA := true` in the BoardConfigPlatform.mk in yoshino
> 
> Please let me know how it goes. I uploaded a change for this to LOS gerrit, but it's private till we have thoroughly tested it.
> 
> edit: And don't forget to remove the taimen libs again before testing of course :)
> 
> edit2: I was first going to fix it by importing the qcom-caf stuff to our device trees. But that's messy and a complete overkill for what we want. At first I thought we need to revert and completely get rid of IMapper 2.1, but that's not the case. This would be much cleaner.

Tested on maple,camera issues fixed,but screen recording green
```
07-30 11:23:08.935  1880  2043 E qdmetadata: Invalid gralloc handle (at 0x753d4dcc00): ver(12/12) ints(25/24) fds(2/2) 
07-30 11:23:08.935  1880  2043 E qdmetadata: validateAndMap: Private handle is invalid - handle:0x753d4dcc00
07-30 11:23:08.944  1880  2043 E qdmetadata: Invalid gralloc handle (at 0x75a9a6eb80): ver(12/12) ints(25/24) fds(2/2) 
07-30 11:23:08.945  1880  2043 E qdmetadata: validateAndMap: Private handle is invalid - handle:0x75a9a6eb80
```

**Comment by shank03** [comment]
Did you clean install ?.. maybe it could change something ?

Just thinking out loud

**Comment by derfelot** [comment]
I didn't test screen recording. so it's very possible that we need to fix something in libqdutils as well.

**Comment by derfelot** [comment]
> > Here's a diff you can apply to `hardware/qcom-caf/msm8998/display` to fix the camera issues:
> > https://pastebin.com/2EiGqsRv
> > You also need to set `TARGET_USES_SONY_STOCK_CAMERA := true` in the BoardConfigPlatform.mk in yoshino
> > Please let me know how it goes. I uploaded a change for this to LOS gerrit, but it's private till we have thoroughly tested it.
> > edit: And don't forget to remove the taimen libs again before testing of course :)
> > edit2: I was first going to fix it by importing the qcom-caf stuff to our device trees. But that's messy and a complete overkill for what we want. At first I thought we need to revert and completely get rid of IMapper 2.1, but that's not the case. This would be much cleaner.
> 
> Tested on maple,camera issues fixed,but screen recording green
> 
> ```
> 07-30 11:23:08.935  1880  2043 E qdmetadata: Invalid gralloc handle (at 0x753d4dcc00): ver(12/12) ints(25/24) fds(2/2) 
> 07-30 11:23:08.935  1880  2043 E qdmetadata: validateAndMap: Private handle is invalid - handle:0x753d4dcc00
> 07-30 11:23:08.944  1880  2043 E qdmetadata: Invalid gralloc handle (at 0x75a9a6eb80): ver(12/12) ints(25/24) fds(2/2) 
> 07-30 11:23:08.945  1880  2043 E qdmetadata: validateAndMap: Private handle is invalid - handle:0x75a9a6eb80
> ```

I just tried screen recording on my device and everything is fine.

did you only push gralloc by any chance? libqdmetadata also depends on gr_priv_handle.h which we modified with this patch.

**Comment by derfelot** [comment]
OK, i think you mean screen casting (wifi display), there i have the same issue.

**Comment by derfelot** [comment]
Right, I think I "fixed" it now, but the way it currently stand it cannot be merged into LOS. I don't really understand my ifndef'ing the dummy variable works, whereas the ifdef doesn't. But please try this diff again and see if all issues are resolved on your side.

Thanks

https://pastebin.com/sRtuzfVG

**Comment by derfelot** [comment]
thanks to a discussion i just had with @nailyk-fr we figured out the issue. Hopefully a final patch will follow tomorrow.

**Comment by idyllic-blue** [comment]
> Right, I think I "fixed" it now, but the way it currently stands it cannot be merged into LOS. I don't really understand my ifndef'ing the dummy variable works, whereas the ifdef doesn't. But please try this diff again and see if all issues are resolved on your side.
> 
> I also don't understand why removing the pragma's fix the numInts issue for the camera using gralloc directly, whereas it is still causing issues with WiFi display when used via libqdMetaData.
> 
> Thanks
> 
> https://pastebin.com/sRtuzfVG

Tested on maple,all issues are resolved.Thank you very much.

**Comment by hakkikaancaliskan** [comment]
> But I'll have a look at gps
@derfelot Is there any progress about this?

**Comment by derfelot** [comment]
no not yet

**Comment by Gabrius99** [comment]
> Right, I think I "fixed" it now, but the way it currently stands it cannot be merged into LOS. I don't really understand my ifndef'ing the dummy variable works, whereas the ifdef doesn't. But please try this diff again and see if all issues are resolved on your side.
> 
> I also don't understand why removing the pragma's fix the numInts issue for the camera using gralloc directly, whereas it is still causing issues with WiFi display when used via libqdMetaData.
> 
> Thanks
> 
> https://pastebin.com/sRtuzfVG

Hi, I tried to compile using these fixes, but gralloc.msm8998.so isn't generated, only gralloc.default.so. Am I missing something?

**Comment by derfelot** [comment]
strange.

Right now, I would just recommend to remove hardware/qcom-caf/msm8998/display and instead clone our branch into it. E.g.:

`git clone -b lineage-17.1-caf-msm8998 hardware/qcom-caf/msm8998/display`

**Comment by derfelot** [comment]
BTW, we are in the process of moving our sources for lilac and poplar to https://github.com/whatawurst

**Comment by derfelot** [comment]
Fix and comments are up

https://github.com/whatawurst/android_device_sony_lilac/pull/1
https://github.com/whatawurst/android_vendor_sony_lilac/pull/1

Poplar will follow.

**Comment by derfelot** [comment]
@cryptomilk : should we close this now?

@ rest: For any other issues, please open a new issue at whatawusrt, preferably in the yoshino repo https://github.com/whatawurst/android_device_sony_yoshino

**Comment by Gabrius99** [comment]
> strange.
> 
> Right now, I would just recommend to remove hardware/qcom-caf/msm8998/display and instead clone our branch into it. E.g.:
> 
> `git clone -b lineage-17.1-caf-msm8998 https://github.com/whatawurst/android_hardware_qcom_display hardware/qcom-caf/msm8998/display`

Very well, I recompiled after cleaning code and with these sources worked. Memory leak is totally gone also on pixel experience and it works well. Night light is also fixed
